### ISSUE TITLE
Language list

### ISSUE THREAD

**Issue by alloy** [fastlane/fastlane_core#36]
After downloading the existing metadata with ‘deliver’, I had a folder named ‘zh-Hans’ for Simplified Chinese. When I renamed that to ‘cmm-Hans’ as per https://github.com/KrauseFx/snapshot/issues/45, I was unable to upload the metadata.

I guess this Radar has been implemented? https://github.com/fastlane/fastlane_core/blob/d22a109e554312956e8cd0615ee3cc58e3a02bc4/lib/fastlane_core/languages.rb#L9

**Comment by KrauseFx** [comment]
That's a good question. So  changed a lot with the recent iTunes Connect update and I haven't yet had a chance to look into the Chinese language support. Also, I'm currently working on the new version of `snapshot`, as the current version still uses UI Automation instead of UI Tests.

Let me know if you find out something about the Chinese language support and if I can already update the `languages.rb` file :+1:
